/**
 * Employer client logos for the Our Clients page.
 * Set `url` when website links are available — cards will become links automatically.
 */
window.GLOBAL_HR_CLIENTS = [
  {
    id: "nippon-express",
    name: "Nippon Express",
    logo: "assets/images/clients/nippon-express.svg",
    industry: "Logistics",
    url: null,
  },
  {
    id: "sembcorp",
    name: "Sembcorp",
    logo: "assets/images/clients/sembcorp.png",
    industry: "Energy & utilities",
    url: null,
  },
  {
    id: "sankyu",
    name: "Sankyu",
    logo: "assets/images/clients/sankyu.png",
    industry: "Logistics",
    url: null,
  },
  {
    id: "st-engineering-marine",
    name: "ST Engineering Marine",
    logo: "assets/images/clients/st-engineering-marine.jpg",
    industry: "Marine",
    url: null,
  },
  {
    id: "gammon-construction",
    name: "Gammon Construction Limited",
    logo: "assets/images/clients/gammon-construction.jpg",
    industry: "Construction",
    url: null,
  },
  {
    id: "penta-ocean-construction",
    name: "Penta-Ocean Construction Co., Ltd.",
    logo: "assets/images/clients/penta-ocean-construction.png",
    industry: "Construction",
    url: null,
  },
  {
    id: "global-offshore-marine",
    name: "Global Offshore Marine Pte Ltd",
    logo: "assets/images/clients/global-offshore-marine.jpg",
    industry: "Marine",
    url: null,
  },
  {
    id: "cccc-singapore",
    name: "China Communications Construction Company (Singapore Branch)",
    logo: "assets/images/clients/cccc-singapore.jpg",
    industry: "Construction",
    url: null,
  },
  {
    id: "alpine-engineering-services",
    name: "Alpine Engineering Services",
    logo: "assets/images/clients/alpine-engineering-services.jpg",
    industry: "Engineering",
    url: null,
  },
  {
    id: "delimax",
    name: "Delimax Pte Ltd",
    logo: "assets/images/clients/delimax.jpg",
    industry: "Engineering",
    url: null,
  },
  {
    id: "engie-services-singapore",
    name: "Engie Services Singapore",
    logo: "assets/images/clients/engie-services-singapore.png",
    industry: "Energy & utilities",
    url: null,
  },
  {
    id: "express-engineering",
    name: "Express Engineering",
    logo: "assets/images/clients/express-engineering.png",
    industry: "Engineering",
    url: null,
  },
  {
    id: "gwell-global",
    name: "Gwell Global",
    logo: "assets/images/clients/gwell-global.jpg",
    industry: "Engineering",
    url: null,
  },
  {
    id: "nam-lee",
    name: "Nam Lee",
    logo: "assets/images/clients/nam-lee.png",
    industry: "Construction",
    url: null,
  },
  {
    id: "rotary-engineering",
    name: "Rotary Engineering",
    logo: "assets/images/clients/rotary-engineering.png",
    industry: "Engineering",
    url: null,
  },
  {
    id: "ugs",
    name: "UGS",
    logo: "assets/images/clients/ugs.png",
    industry: "Engineering",
    url: null,
  },
  {
    id: "utoc",
    name: "UTOC",
    logo: "assets/images/clients/utoc.png",
    industry: "Construction",
    url: null,
  },
  {
    id: "yhh-engineering",
    name: "Y.H.H Engineering",
    logo: "assets/images/clients/yhh-engineering.png",
    industry: "Engineering",
    url: null,
  },
  {
    id: "cesco",
    name: "CESCO",
    logo: "assets/images/clients/cesco.png",
    industry: "Engineering",
    url: null,
  },
];
