(function () {
  window.globalHrDemoJobs = [
    {
      id: "demo-001",
      is_sample: true,
      title: "Marine Fitter",
      company: "Jurong Shipyard (via Global HR)",
      location: "Singapore",
      job_type: "Full-time",
      industry: "Marine / Shipyard",
      description:
        "Experienced marine fitters for vessel repair and new-build projects. Must pass client interview briefing and medical checks before deployment.",
      apply_email: "jc@globalhrss.com",
      status: "active",
      created_at: "2026-05-12",
    },
    {
      id: "demo-002",
      title: "Certified Welder (6G)",
      company: "Keppel / Nakilat Projects",
      location: "Singapore",
      job_type: "Contract",
      industry: "Marine / Shipyard",
      description:
        "Welders with proven 6G certification and shipyard safety training. Pre-departure briefing and skills assessment provided by Global HR in Myanmar.",
      apply_email: "jc@globalhrss.com",
      status: "active",
      created_at: "2026-05-10",
    },
    {
      id: "demo-003",
      is_sample: true,
      title: "Forklift Operator",
      company: "Sankyu Singapore",
      location: "Singapore",
      job_type: "Full-time",
      industry: "Logistics / Warehousing",
      description:
        "Licensed forklift drivers for warehouse and port operations. Selected candidates attend Global HR pre-placement briefing before mobilisation.",
      apply_email: "jc@globalhrss.com",
      status: "active",
      created_at: "2026-05-08",
    },
    {
      id: "demo-004",
      is_sample: true,
      title: "Healthcare Assistant (HSS)",
      company: "Healthcare Placement Partner",
      location: "Singapore",
      job_type: "Full-time",
      industry: "Healthcare",
      description:
        "Patient-care support roles in hospital and community settings. HSS training and interview preparation available through Global HR.",
      apply_email: "jc@globalhrss.com",
      status: "active",
      created_at: "2026-05-06",
    },
    {
      id: "demo-005",
      is_sample: true,
      title: "Mechanical Technician",
      company: "Industrial Client — Myanmar",
      location: "Yangon",
      job_type: "Full-time",
      industry: "Engineering",
      description:
        "Maintenance and production technicians for manufacturing plants. Interview coaching and screening support at our Yangon office.",
      apply_email: "jc@globalhrss.com",
      status: "active",
      created_at: "2026-05-04",
    },
    {
      id: "demo-006",
      is_sample: true,
      title: "Scaffolding Supervisor",
      company: "Singapore Worksites",
      location: "Singapore",
      job_type: "Full-time",
      industry: "Construction",
      description:
        "Supervisors with scaffolding safety training and site leadership experience. Practical scaffolding training can be arranged before deployment.",
      apply_email: "jc@globalhrss.com",
      status: "active",
      created_at: "2026-05-02",
    },
  ];
})();
