const SUPABASE_URL = "https://qtoahowstzrvbhmddnbr.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0b2Fob3dzdHpydmJobWRkbmJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgxMjcwNjksImV4cCI6MjA5MzcwMzA2OX0.wdPjtpQmQxkluV3NhyFSt-ocM6HSOMt-Z5GmAvXmwR8";
const supabase = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
